### ISSUE TITLE
Extrapolation with loess needed

### ISSUE THREAD

**Issue by soob-kim** [hyu-kim/mds-hypothesis-testing#12]
[mm.R](https://github.com/hyu-kim/mds-hypothesis-testing/blob/0fbc8ed1c3c346fdfc16845dc1dff76b4d0ad435/data/mm.R) 파일의 `pair_by_rank` 함수에서, 우리가 loess를 사용하기 때문에 주어진 데이터의 범위에서 벗어나는 새로운 데이터로 predict를 하려고 하면 NA를 주는 에러가 있어,
그래서 `mm_cmds(nit=15, lambda=0.5, z0=zmds1, D=distmat1, y=y1)` 을 돌리면 NA를 줘

[여기](https://stackoverflow.com/questions/27796368/r-loess-prediction-returns-na)에서처럼, 
```
pair_by_rank <- function(D, z, y, fun){
  f0_sorted <- get_p(d=D, trt=y, fun=fun)$ratio_all
  fz_sorted <- get_p(mat=z, trt=y, fun=fun)$ratio_all
  N <- length(f0_sorted)
  mat_pair <- matrix(0, nrow=N, ncol=2)
  mat_pair[,1] <- f0_sorted
  mat_pair[,2] <- fz_sorted
  df_pair <- data.frame(data=mat_pair)
  colnames(df_pair) <- c('F0','Fz')
  loess_f <- loess(Fz ~ F0, data=df_pair, span=0.10,
                   control=loess.control(surface="direct")) ## Add this part
  return(list(pair=mat_pair, model=loess_f))
}
```

이렇게 하면 그 문제는 일단 사라져. 함수 수정할 때 이 부분도 참고해줘!

**Comment by hyu-kim** [comment]
맞아 그게 loess의 한계인데 너가 알려준대로 옵션 추가할게, 땡큐

근데 디폴트로 1000번 permute하도록 되어있어서 
범위를 벗어나는 F통계량이 인풋으로 들어가기 쉽지 않을텐데..?

나도 mm.R 짜다가 비슷한 문제가 있었는데, 알고보니 당시 내 코드의 F통계량이 잘못되어 있었더라고
너도 한 번 확인해보면 좋을 것 같아서!

**Comment by soob-kim** [comment]
mm_cmds 함수 안에서 F값이 계산되는 거 아닌가? 일단 한번 살펴볼게. 👍
