### ISSUE TITLE
can't find zmds1

### ISSUE THREAD

**Issue by hyu-kim** [hyu-kim/mds-hypothesis-testing#2]
수빈 @soob-kim , 너가 작성한 gradient descent 코드를 살펴보는 중인데 (`data/gd.R`) 막히는 부분이 있어서. 130번째 줄을 보면 아래와 같이 되어있는데 ([링크](https://github.com/hyu-kim/mds-hypothesis-testing/blob/d4c4d6c9642e1921a45c112901bceb2490beb4b3/data/gd.R#L130))

`tmp <- gd_mds(nit = 100, D = as.matrix(dist1), z0 = zmds1)`

혹시 `zmds1`이 어디서 온 건지 설명해줄 수 있을까?

형석

**Comment by soob-kim** [comment]
파일을 빼먹었어 미안!
initial value이고 plain 하게 mds로 한 결과야.
https://github.com/hyu-kim/mds-hypothesis-testing/blob/soobin/data/data.R 
이 파일의 결과로 넣었어.
pull request가 왜 안 되는지는 모르겠어. 이따가 해결해볼게!!
