### ISSUE TITLE
derivative for line 115 in gd.R

### ISSUE THREAD

**Issue by hyu-kim** [hyu-kim/mds-hypothesis-testing#5]
수빈아 gradient descent 함수 미분 꼴 형태를 확인하는 중이었는데, F statistic 미분 항에 분모 식이 빠진 것 같아서 코멘트를 남겨. 

115 `      d_g <- 4 * (N-a)/a * sign(Fz_cur - F0) * (tmp11 * tmp12 - tmp21 * tmp22)` ([링크](https://github.com/hyu-kim/mds-hypothesis-testing/blob/dcd5b95d944f24bddb163ddc7dfc4765470a7e5f/data/gd.R#L115))

내가 맞게 본 건지 확인해줄 수 있을까? 

Overleaf 너가 작성한 문서 formulation.tex ([링크](https://www.overleaf.com/8439881286bnbbcpmhfpdj)) 에도 같은 코멘트 남겼어

@soob-kim

**Comment by soob-kim** [comment]
응 맞게 본 거 같아 분모를 빠트렸어

**Comment by hyu-kim** [comment]
오키 그럼 이따 집에가서 코드 고칠게!

Thanks,
Hyu

Sent from my iPhone
________________________________
