### ISSUE TITLE
y1 vs y1s in mm.R

### ISSUE THREAD

**Issue by soob-kim** [hyu-kim/mds-hypothesis-testing#9]
[mm.R 파일](https://github.com/hyu-kim/mds-hypothesis-testing/blob/main/data/mm.R)에서 데이터의 레이블(y)값을 어떻게 둔 건지 궁금해서 이슈를 만들었어
데이터에서 label은 pt+, pt-값으로 나오는 애들인 줄 알았는데 아닌가?
근데 코드에서 label로 사용한 y1s는 result/labels_site1.txt 에서 가져오던데,
1) 이 텍스트 파일의 각 열이 무슨 값들인지,
2) 텍스트 파일의 값과 데이터에서 가져온 y1 (ifelse(site1@sam_data$Treatment == "Pt +", 1, 2)) 의 차이가 뭔지 궁금해

**Comment by hyu-kim** [comment]
`labels_site1 / 2.txt`파일들은,
예전에 내가 제안했었던 레이블 섞기를 통해 나온 케이스 중 두 개를 각각 저장한 것인데, 
(케이스 두 개를 어떻게 선별했는가는 여기 따로 적지는 않을게, 근데 궁금하면 알려줘)

1. 각 열은 선별된 두 개의 케이스중 각 하나씩을 뜻하고
2. 텍스트 파일의 값 `1`, `2`는 기존 데이터에서 사용하는 레이블 `pt+`, `pt-`와 개념적으로 동일해

이해가 더 안되는 부분 있으면 알려줘

**Comment by hyu-kim** [comment]
참고로 예시 시각화 결과들은 `labels_site2.txt`에 기반한 것이라서, line 140을 조금 수정했어

**Comment by soob-kim** [comment]
오케이 알았어,
그런데 line 140에 
obmm_x <- mm_cmds(nit=15, lambda=0.3, z0=zmds2, D=distmat2, **_y=y2s[,1]_**)  # just an example. replace x with any number you want
이렇게 되어야 하지 않는지 확인해주라 (아래 시각화는 y=y2s[,1] 를 썼길래)

**Comment by hyu-kim** [comment]
응 너가 맞아, line140은 내가 실제로 돌렸던 구문은 아니었어서  자꾸 틀리네 미안

**Comment by soob-kim** [comment]
오케이~!!
